=== marcello3d/alt/js/alt/squeal/stl/squeal.xsd
<xs:schema targetNamespace="squeal.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ss="squeal.xsd">

  <xs:annotation>
    <xs:documentation xml:lang="en">
     SQL Schema definition for creating and managing databases.
     by Marcello Bastea-Forte (marcello@cellosoft.com)
     Version 0.1
    </xs:documentation>
  </xs:annotation>
  
  <xs:element name="schema">
  
  <xs:annotation>
    <xs:documentation xml:lang="en">
     The top-level element is a schema tag with 0 or more types, database, or table tags.
    </xs:documentation>
  </xs:annotation>
  
   <xs:complexType>
    <xs:sequence>
     <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="types"><xs:complexType><xs:sequence><xs:element name="type" type="ss:Type" minOccurs="0" maxOccurs="unbounded" /></xs:sequence></xs:complexType></xs:element>
      <xs:element name="database" type="ss:Database" />
      <xs:element name="table" type="ss:Table" />
     </xs:choice>
    </xs:sequence>
   </xs:complexType>
  </xs:element>
  
  <xs:complexType name="Database">
   <xs:sequence>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
     <xs:element name="type" type="ss:Type" />
     <xs:element name="table" type="ss:Table" />
     </xs:choice>
   </xs:sequence>
   <xs:attribute name="name" type="ss:Name" use="optional" />
  </xs:complexType>
  
  <xs:complexType name="Type">
        <xs:sequence>
        	<xs:choice maxOccurs="unbounded" minOccurs="0"><xs:element name="option" type="ss:Option"></xs:element><xs:element name="define-constraint" type="ss:DefineConstraint">
        	</xs:element><xs:element name="constrain" type="ss:Constrain"></xs:element></xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="ss:TypeName" use="required" />
   <xs:attribute name="base" type="ss:TypeName" use="required" />
  </xs:complexType>
  
  <xs:simpleType name="Name">
   <xs:restriction base="xs:string">
     <xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]+"/>
   </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="TableName">
   <xs:restriction base="xs:string">
     <xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*(.[a-zA-Z_][a-zA-Z0-9_]*)*"/>
   </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="TypeName">
   <xs:restriction base="xs:string">
     <xs:pattern value=".+"/>
   </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="Table">
   <xs:sequence>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
     <xs:element name="field">
      <xs:complexType>
        <xs:attribute name="name" type="ss:Name" use="required" />
        <xs:attribute name="type" type="ss:TypeName" use="required" />
        <xs:attribute name="index" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="required" type="xs:boolean" use="optional" default="false" />
      </xs:complexType>
     </xs:element>
     <xs:element name="link">
      <xs:complexType>
        <xs:attribute name="name" type="ss:Name" use="required" />
        <xs:attribute name="table" type="ss:TableName" use="required" />
        <xs:attribute name="index" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="required" type="xs:boolean" use="optional" default="false" />
      </xs:complexType>
     </xs:element>
     <xs:element name="type" type="ss:Type" />
     <xs:element name="table" type="ss:Table" />
    </xs:choice>
   </xs:sequence>
   
   <xs:attribute name="name" type="ss:Name" use="required" />
   <xs:attribute name="parent" type="ss:TableName" use="optional" />
   <xs:attribute name="unique" type="xs:boolean" use="optional" default="false"  />
   <xs:attribute name="required" type="xs:boolean" use="optional" default="false" />
   
  </xs:complexType>


  <xs:complexType name="Constrain">
  	<xs:attribute name="type" type="xs:string"></xs:attribute>
  	<xs:anyAttribute></xs:anyAttribute>
  </xs:complexType>

  <xs:complexType name="Option">
        <xs:sequence>
        </xs:sequence>
        <xs:attribute name="value" type="xs:string"></xs:attribute>
  </xs:complexType>
  
    <xs:complexType name="DefineConstraint"></xs:complexType>

    <xs:group name="ModelGroupDefinition">
    	<xs:sequence></xs:sequence>
    </xs:group>
</xs:schema>

=== marcello3d/alt/src/examples/sample-squeal.xml
<?xml version="1.0"?>
<schema
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="squeal.xsd"> 
<types>
 <description>
  Defines some basic types
 </description>

 <type name="username" base="sql:char(15)">
  <constrain type="length" min="3" max="15"/>
  <constrain type="ereg" value="^[a-zA-Z0-9]+$"/>
 </type>
 <type name="password" base="sql:char(10)">
  <constrain type="length" min="6" max="15"/>
  <constrain type="ereg" value="^[a-zA-Z0-9]+$"/>
 </type>
 <type name="email" base="sql:char(255)">
  <constrain type="length" min="5" max="255"/>
  <constrain type="ereg" value="^.+@.+$"/>
 </type>
 <type name="string" base="sql:varchar(255)" /> 
 
 <type name="title" base="string" default="'No title'" />
 <type name="message" base="sql:text" />
 <type name="date" base="sql:datetime">
   <value name="default" value="sql:NOW()" />
   <value name="yesterday" value="sql:DATE_SUB(NOW(),INTERVAL 1 DAY)" />
 </type>
</types>

<database name="network"> 

 <table name="user">
  <field name="username" type="username" index="unique" required="true" />
  <field name="password" type="password" required="true" />
  <field name="email" type="email" index="true" required="true" />
  <field name="reg" type="date" required="true" />
  <field name="access" type="date" />
 </table>
 <table name="memo">
  <link name="recipient" table="user" index="true" required="true" />
  <link name="sender" table="user" index="true" required="false" />
  <field name="date" type="date" required="true" />
  <field name="status" type="enum">
   <option name="Unread"  value="unread" />
   <option name="Read"    value="read"   />
   <option name="Replied" value="replied"/>
  </field>
  <field name="subject" type="title" />
  <field name="body" type="message" />
 </table>

</database>

<database name="forum">

	<type name="boolean" base="sql:tinyint" default="0" />
 <table name="thread">
  <link name="author" table="network.user" index="true" />
  <field name="date" type="date" />
  <field name="subject" type="title" required="true" index="fulltext" />
  
  <table name="description" unique="true">
   <field name="description" type="message" index="fulltext" /> 
  </table>
  
  
      
  <table name="personal">
   <link name="user" table="network.user" index="unique" />
   <field name="read" type="boolean" />
  </table>
      
  <view name="recent">
   <param name="perPage" type="integer" />
   <param name="currentUser" type="member" required="false" />
  <!-- <link name="" table="personal" on="`member`=$currentUser" /> -->
  </view>
 
  <table name="comment">
   <link name="author" table="network.user" index="true" />
   <field name="date" type="date" />
   <field name="body" type="message" index="fulltext" />
   
   <table name="vote">
    <link name="user" table="network.user" index="unique" />
    <field name="favorite" type="boolean" required="true" />
   </table>
   
  </table>

 </table>
 
 <table name="node">
  <link name="parent" table="node" index="true" />
  <field name="author" type="network.user" index="true" />
  <field name="title" type="title" required="true" index="fulltext" />
  <field name="body" type="message" required="true" index="fulltext" />
 </table>
</database>

	
</schema>

=== marcello3d/alt/js/alt/squeal/stl/standard-types.xml
<?xml version="1.0"?>
<schema
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../xsd/squeal.xsd">
 
 <types>
  <type name="SQL">
    <define-method name="getSQLType"/>
    <define-constraint name="regexp"	type="client" />
  </type>
  
  <type name="String" base="SQL"		size="255">
    <define-constraint name="length"	type="client" />
  </type>
  
  <type name="Binary" base="String"		size="255">
    <define-constraint name="length"	type="client" />
  </type>
  
  <type name="Integer" base="SQL">
    <define-constraint name="range"		type="client" />
    <define-constraint name="minimum"	type="client" />
    <define-constraint name="maximum"	type="client" />
    <define-constraint name="positive"	type="client" />
    <define-constraint name="negative"	type="client" />
  </type>
 
  <type name="Real">
    <define-constraint name="range"		type="client" />
    <define-constraint name="minimum"	type="client" />
    <define-constraint name="maximum"	type="client" />
    <define-constraint name="positive"	type="client" />
    <define-constraint name="negative"	type="client" />
  </type>
  
  <type name="Date" base="SQL">
    <define-constraint name="range"		type="client" />
    <define-constraint name="past"		type="client" />
    <define-constraint name="future"	type="client" />
    
    <constrain name="regexp" match="^[0-9]{4}-[01][0-9]-[0-3][0-9]$" />
  </type>
  
  <type name="Time" base="SQL">
    <define-constraint name="range"		type="client" />
    <define-constraint name="past"		type="client" />
    <define-constraint name="future"	type="client" />
    
    <constrain name="regexp" match="^[0-2][0-9]:[0-5][0-9]$" />
  </type>
  
  <type name="Timestamp" base="SQL">
    <define-constraint name="range"		type="client" />
    <define-constraint name="past"		type="client" />
    <define-constraint name="future"	type="client" />
 
    <constrain name="regexp" 
   			 match="^[0-9]{4}-[01][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]{2}$" />
  </type>
  
  <type name="Enum" base="SQL" />
  
  <type name="Set" base="SQL">
    <define-constraint name="range"		type="client" />
    <define-constraint name="minimum"	type="client" />
    <define-constraint name="maximum"	type="client" />
  </type>
 </types>
</schema>
